import experienceImage from '../assets/experience-tile.svg'
import openSourceImage from '../assets/open-source-tile.svg'
import resumePdfImage from '../assets/resume-pdf-tile.svg'
import techStackImage from '../assets/tech-stack-tile.svg'
import writingBlogImage from '../assets/writing-blog-tile.svg'

export type MediaType = 'gif' | 'image' | 'placeholder' | 'video'
export type TileSize = 'hero' | 'small' | 'tall' | 'wide'
export type TileTone = 'blue' | 'coral' | 'gold' | 'graphite' | 'mint' | 'violet'

export interface GalleryItem {
  id: string
  title: string
  source?: string
  mediaType: MediaType
  tileSize: TileSize
  tone: TileTone
  glyph: string
  link?: string
}

export interface GallerySection {
  id: string
  label: string
  items: GalleryItem[]
}

// Drop photos, GIFs, or short videos into public/assets/media and reference them as /assets/media/file-name.ext.
export const GALLERY_SECTIONS: GallerySection[] = [
  {
    id: 'profile',
    label: 'Profile',
    items: [
      {
        id: 'about',
        title: 'About Me',
        source: '/images/about-me.jpeg',
        mediaType: 'image',
        tileSize: 'hero',
        tone: 'mint',
        glyph: 'JV',
        link: 'https://about-me-azo.pages.dev',
      },
      {
        id: 'github',
        title: 'GitHub',
        mediaType: 'image',
        tileSize: 'small',
        tone: 'graphite',
        glyph: 'GH',
        link: 'https://github.com/JuanVillegas95',
        source: 'https://camo.githubusercontent.com/e7e2e4c44e3f14bea8123598db8f7dc62fa0c77193e2e7b962bf871777cba717/68747470733a2f2f6564656e742e6769746875622e696f2f537570657254696e7949636f6e732f696d616765732f706e672f6769746875622e706e67'
      },
      {
        id: 'linkedin',
        title: 'LinkedIn',
        mediaType: 'image',
        tileSize: 'small',
         source: 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/81/LinkedIn_icon.svg/1280px-LinkedIn_icon.svg.png',
        tone: 'blue',
        glyph: 'IN',
        link: 'https://www.linkedin.com/in/juan-villegas97/',
      },
      {
        id: 'resume',
        title: 'Resume',
        source: 'https://cdn-icons-png.flaticon.com/512/6588/6588143.png',
        mediaType: 'image',
        tileSize: 'small',
        tone: 'graphite',
        glyph: 'RM',
        link: 'https://github.com/JuanVillegas95',
      },
      {
        id: 'linkedin',
        title: 'LinkedIn',
        mediaType: 'image',
        tileSize: 'tall',
         source: 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/81/LinkedIn_icon.svg/1280px-LinkedIn_icon.svg.png',
        tone: 'blue',
        glyph: 'IN',
        link: 'https://www.linkedin.com/in/juan-villegas97/',
      },
      {
        id: 'contact-me',
        title: 'Contact me',
        source: 'https://cdn.prod.website-files.com/645c01ff2d797fbf2d960bfc/687426d1bdde1d9ca50dbada_apple-mail.png',
        mediaType: 'image',
        tileSize: 'tall',
        tone: 'coral',
        glyph: 'W',
        link: '#',
      },
      {
        id: 'contact-me',
        title: 'Contact me',
        source: 'https://www.ellenstipsforios.com/wp-content/uploads/2022/02/Mail-Featured-image.png',
        mediaType: 'image',
        tileSize: 'small',
        tone: 'blue',
        glyph: 'CM',
        link: '#',
      },
      {
        id: 'x-mas',
        title: 'x-mas',
        source: '/images/x-mas.jpeg',
        mediaType: 'image',
        tileSize: 'wide',
        tone: 'blue',
        glyph: 'XM',
        link: 'https://824066e3.honecita-x-mas.pages.dev',
      },
      {
        id: 'music-room',
        title: 'Music Room',
        source: '/music/hikari%20%E5%85%89/img.jpeg',
        mediaType: 'image',
        tileSize: 'small',
        tone: 'gold',
        glyph: 'MR',
        link: '#',
      },
      {
        id: 'lab',
        title: 'Lab',
        mediaType: 'placeholder',
        tileSize: 'small',
        tone: 'violet',
        glyph: 'LB',
        link: '#',
      },
            {
        id: 'lab',
        title: 'Lab',
        mediaType: 'placeholder',
        tileSize: 'small',
        tone: 'violet',
        glyph: 'LB',
        link: '#',
      },
            {
        id: 'lab',
        title: 'Lab',
        mediaType: 'placeholder',
        tileSize: 'small',
        tone: 'violet',
        glyph: 'LB',
        link: '#',
      },
      {
        id: 'notes',
        title: 'Notes',
        source: writingBlogImage,
        mediaType: 'image',
        tileSize: 'wide',
        tone: 'coral',
        glyph: 'NT',
        link: '#',
      },
    ],
  },
  {
    id: 'work',
    label: 'Work',
    items: [
      {
        id: 'experience',
        title: 'Experience',
        source: experienceImage,
        mediaType: 'image',
        tileSize: 'hero',
        tone: 'blue',
        glyph: 'EX',
        link: '#',
      },
      {
        id: 'tech-stack',
        title: 'Tech Stack',
        source: techStackImage,
        mediaType: 'image',
        tileSize: 'tall',
        tone: 'violet',
        glyph: 'TS',
        link: '#',
      },
      {
        id: 'resume',
        title: 'Resume',
        source: resumePdfImage,
        mediaType: 'image',
        tileSize: 'small',
        tone: 'gold',
        glyph: 'CV',
        link: '#',
      },
      {
        id: 'open-source',
        title: 'Open Source',
        source: openSourceImage,
        mediaType: 'image',
        tileSize: 'wide',
        tone: 'graphite',
        glyph: 'OS',
        link: 'https://github.com/JuanVillegas95',
      },
      {
        id: 'lilium',
        title: 'Lilium',
        source: '/music/lilium/img.jpeg',
        mediaType: 'image',
        tileSize: 'wide',
        tone: 'coral',
        glyph: 'LI',
        link: '#',
      },
      {
        id: 'build-notes',
        title: 'Build Notes',
        mediaType: 'placeholder',
        tileSize: 'small',
        tone: 'mint',
        glyph: 'BN',
        link: '#',
      },
      {
        id: 'ambient-loop',
        title: 'Ambient Loop',
        mediaType: 'gif',
        tileSize: 'small',
        tone: 'violet',
        glyph: 'AL',
        link: '#',
      },
      {
        id: 'systems',
        title: 'Systems',
        mediaType: 'placeholder',
        tileSize: 'wide',
        tone: 'graphite',
        glyph: 'SY',
        link: '#',
      },
      {
        id: 'homelab',
        title: 'Homelab',
        mediaType: 'placeholder',
        tileSize: 'wide',
        tone: 'mint',
        glyph: 'HL',
        link: '#',
      },
      {
        id: 'toolkit',
        title: 'Toolkit',
        source: techStackImage,
        mediaType: 'image',
        tileSize: 'tall',
        tone: 'blue',
        glyph: 'TK',
        link: '#',
      },
      {
        id: 'ideas',
        title: 'Ideas',
        mediaType: 'placeholder',
        tileSize: 'small',
        tone: 'gold',
        glyph: 'ID',
        link: '#',
      },
    ],
  },
  {
    id: 'media',
    label: 'Media',
    items: [
      {
        id: 'media-drop',
        title: 'Media Drop',
        mediaType: 'placeholder',
        tileSize: 'hero',
        tone: 'coral',
        glyph: 'MD',
        link: '#',
      },
      {
        id: 'hikari',
        title: 'Hikari',
        source: '/music/hikari%20%E5%85%89/img.jpeg',
        mediaType: 'image',
        tileSize: 'wide',
        tone: 'gold',
        glyph: 'HI',
        link: '#',
      },
      {
        id: 'photo-strip',
        title: 'Photo Strip',
        mediaType: 'placeholder',
        tileSize: 'tall',
        tone: 'blue',
        glyph: 'PS',
        link: '#',
      },
      {
        id: 'gif-slot',
        title: 'GIF Slot',
        mediaType: 'gif',
        tileSize: 'small',
        tone: 'mint',
        glyph: 'GF',
        link: '#',
      },
      {
        id: 'video-slot',
        title: 'Video Slot',
        mediaType: 'video',
        tileSize: 'wide',
        tone: 'graphite',
        glyph: 'VD',
        link: '#',
      },
      {
        id: 'archive',
        title: 'Archive',
        mediaType: 'placeholder',
        tileSize: 'small',
        tone: 'violet',
        glyph: 'AR',
        link: '#',
      },
      {
        id: 'frame-set',
        title: 'Frame Set',
        mediaType: 'placeholder',
        tileSize: 'wide',
        tone: 'blue',
        glyph: 'FS',
        link: '#',
      },
      {
        id: 'audio-log',
        title: 'Audio Log',
        source: '/music/clair-obscure/img.jpeg',
        mediaType: 'image',
        tileSize: 'wide',
        tone: 'gold',
        glyph: 'AU',
        link: '#',
      },
      {
        id: 'clip-bank',
        title: 'Clip Bank',
        mediaType: 'video',
        tileSize: 'wide',
        tone: 'graphite',
        glyph: 'CB',
        link: '#',
      },
      {
        id: 'snapshots',
        title: 'Snapshots',
        source: '/music/lilium/img.jpeg',
        mediaType: 'image',
        tileSize: 'wide',
        tone: 'coral',
        glyph: 'SN',
        link: '#',
      },
    ],
  },
]

export const GALLERY_PAGE_COUNT = GALLERY_SECTIONS.length
